Rewrite CI
Signed-off-by: Hendrix-Shen <HendrixShen@hendrixshen.top>

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -1,76 +1,120 @@
-name: Publish Release
+name: step.publish
 on:
-  release:
-    types:
-      - published
+  workflow_call:
+    inputs:
+      publish_channel:
+        type: string
+        required: true
+      publish_mc_ver:
+        type: string
+        required: true
+      publish_platform:
+        type: string
+        required: true
+      publish_target_release_tag:
+        description: |-
+          The tag of the release you want to append the artifact to.
+        type: string
+        required: true
 jobs:
-  build:
-    strategy:
-      matrix:
-        java: [ 17 ]
-        os: [ ubuntu-20.04 ]
-    runs-on: ${{ matrix.os }}
+  publish:
+    runs-on: ubuntu-latest
+    # Allow the mod publish step to add assets to release
+    # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
+    permissions:
+      contents: write
     steps:
-      - name: checkout repository
-        uses: actions/checkout@v3
+      - name: Checkout the sources
+        uses: actions/checkout@v4
         with:
           fetch-depth: 0
-      - name: setup jdk ${{ matrix.java }}
-        uses: actions/setup-java@v3
+      - name: Download build artifacts
+        uses: actions/download-artifact@v4
         with:
-          distribution: 'adopt'
-          java-version: ${{ matrix.java }}
-      - name: Cache Gradle packages
-        uses: actions/cache@v3
+          name: build-artifacts
+          path: build-artifacts
+      - name: Get git info
+        id: get_git_info
+        run: |
+          short_sha=$(echo ${GITHUB_SHA} | cut -c1-7)
+          commit_count=$(git log | grep -e '^commit [a-zA-Z0-9]*' | wc -l)
+          echo "short_sha=$short_sha" >> $GITHUB_OUTPUT
+          echo "commit_count=$commit_count" >> $GITHUB_OUTPUT
+      - name: Get github release information
+        if: ${{ github.event_name == 'workflow_dispatch' }}
+        id: get_release
+        uses: cardinalby/git-get-release-action@1.2.5
+        env:
+          GITHUB_TOKEN: ${{ github.token }}
         with:
-          path: |
-            ~/.gradle/caches
-            ./.gradle/loom-caches
-            ~/.gradle/wrapper
-          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
-      - name: make gradle wrapper executable
-        run: chmod +x ./gradlew
-      - name: preprocessResources
+          tag: ${{ github.event.inputs.publish_target_release_tag }}
+      - name: Read Properties mod info
+        id: mod_info
+        uses: christian-draeger/read-properties@1.1.1
+        with:
+          path: gradle.properties
+          properties: 'mod.name mod.version'
+      - name: Prepare file information
+        id: file_info
+        run: |
+          shopt -s extglob
+          FILE_PATHS=$(ls ${{ format('build-artifacts/{0}-{1}/build/libs/!(*-@(dev|sources|javadoc)).jar', inputs.publish_mc_ver, inputs.publish_platform) }})
+          
+          if (( ${#FILE_PATHS[@]} != 1 )); then
+              echo "Error: Found ${#FILE_PATHS[@]} files, expected exactly 1"
+              exit 1
+          else
+              FILE_PATH=${FILE_PATHS[0]}
+          fi
+          
+          FILE_NAME=$(basename $FILE_PATH)
+          FILE_HASH=$(sha256sum $FILE_PATH | awk '{ print $1 }')
+          echo "path=$FILE_PATH" >> $GITHUB_OUTPUT
+          echo "name=$FILE_NAME" >> $GITHUB_OUTPUT
+          echo "hash=$FILE_HASH" >> $GITHUB_OUTPUT
+          cat $GITHUB_OUTPUT
+      - name: Prepare changelog
+        if: ${{ inputs.publish_channel == 'stable' }}
+        uses: actions/github-script@v7
+        id: changelog_release
+        with:
+          script: return process.env.CHANGELOG
+          result-encoding: string
         env:
-          BUILD_TYPE: "RELEASE"
-        run: ./gradlew preprocessResources
-      - name: build
-        env:
-          BUILD_TYPE: "RELEASE"
-        run: ./gradlew build
+          CHANGELOG: |-
+            ${{ format('{0}{1}', github.event.release.body, steps.get_release.outputs.body) }}
+            
+            -------
+            
+            Build Information
+            
+            - File name: `${{ steps.file_info.outputs.name }}`
+            - SHA-256: `${{ steps.file_info.outputs.hash }}`
+            - Built from: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
       - name: Publish Minecraft Mods
-        uses: Kir-Antipov/mc-publish@v3.2
+        if: ${{ inputs.publish_channel == 'stable' }}
+        uses: Kir-Antipov/mc-publish@v3.3
         with:
           modrinth-id: SFO4Ca80
           modrinth-token: ${{ secrets.MODRINTH }}
-
           curseforge-id: 525510
           curseforge-token: ${{ secrets.CF_API_TOKEN }}
-
+          github-tag: ${{ inputs.publish_target_release_tag }}
           github-token: ${{ secrets.GITHUB_TOKEN }}
-
-          files-primary: fabricWrapper/build/libs/!(*-@(dev|sources|javadoc)).jar
-          files-secondary: fabricWrapper/build/tmp/submods/META-INF/jars/!(*-@(dev|sources|javadoc)).jar
-
-          name: ''
+          github-generate-changelog: true
+          files: ${{ steps.file_info.outputs.path }}
+          name: ${{ format('{0} {1}.{2} for Minecraft {3} ({4})', steps.mod_info.outputs.mod-name, steps.mod_info.outputs.mod-version, steps.get_git_info.outputs.commit_count, inputs.publish_mc_ver, inputs.publish_platform) }}
+          version: ${{ format('mc-{0}-{1}-v{2}.{3}', inputs.publish_mc_ver, inputs.publish_platform, steps.mod_info.outputs.mod-version, steps.get_git_info.outputs.commit_count) }}
           version-type: release
-          changelog: ${{ github.event.release.body }}
-
-          loaders: fabric
+          github-changelog: ${{ format('{0}{1}', github.event.release.body, steps.get_release.outputs.body) }}
+          modrinth-changelog: ${{ steps.changelog.outputs.result }}
+          curseforge-changelog: ${{ steps.changelog.outputs.result }}
+          loaders: |
+            ${{ inputs.publish_platform }}
           game-versions: |
-            1.14.4
-            1.15.2
-            1.16.5
-            1.17.1
-            1.18.2
-            1.19.2
-            1.19.3
-            1.19.4
-            1.20.1
-            1.20.2
-            1.20.4
-
-          version-resolver: any
-
-          retry-attempts: 3
+            ${{ inputs.publish_mc_ver }}
+          game-version-filter: any
+          dependencies: |
+            malilib(optional)
+          retry-attempts: 2
           retry-delay: 10000
